name: Build
on: [push, pull_request_target]
env:
  GITHUB_CLIENT_MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: build-${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Get Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies --stacktrace
      - name: Run Tests
        run: ./gradlew check --stacktrace
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: build-${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Get Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: ./gradlew androidDependencies --stacktrace
      - name: Run Tests Firebase
        env:
          GCLOUD_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
          FCM_API_KEY: ${{ secrets.FCM_API_KEY }}
        run: ./gradlew runInstrumentedTestsOnFirebase  --stacktrace
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-2
          key: lint--${{ hashFiles('build.gradle') }}-${{ hashFiles('dependencies.gradle') }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('app/build.gradle') }}
      - name: Lint
        run: ./gradlew lint --stacktrace
